export const CURRENCY_NAMES: Record<string, { name: string; nameCn: string }> = {
  AED: { name: "UAE Dirham", nameCn: "阿联酋迪拉姆" },
  AFN: { name: "Afghan Afghani", nameCn: "阿富汗尼" },
  ALL: { name: "Albanian Lek", nameCn: "阿尔巴尼亚列克" },
  AMD: { name: "Armenian Dram", nameCn: "亚美尼亚德拉姆" },
  ANG: { name: "Netherlands Antillean Guilder", nameCn: "荷属安的列斯盾" },
  AOA: { name: "Angolan Kwanza", nameCn: "安哥拉宽扎" },
  ARS: { name: "Argentine Peso", nameCn: "阿根廷比索" },
  AUD: { name: "Australian Dollar", nameCn: "澳元" },
  AWG: { name: "Aruban Florin", nameCn: "阿鲁巴弗罗林" },
  AZN: { name: "Azerbaijani Manat", nameCn: "阿塞拜疆马纳特" },
  BAM: { name: "Bosnia Mark", nameCn: "波黑马克" },
  BBD: { name: "Barbados Dollar", nameCn: "巴巴多斯元" },
  BDT: { name: "Bangladeshi Taka", nameCn: "孟加拉塔卡" },
  BGN: { name: "Bulgarian Lev", nameCn: "保加利亚列弗" },
  BHD: { name: "Bahraini Dinar", nameCn: "巴林第纳尔" },
  BIF: { name: "Burundian Franc", nameCn: "布隆迪法郎" },
  BMD: { name: "Bermudian Dollar", nameCn: "百慕大元" },
  BND: { name: "Brunei Dollar", nameCn: "文莱元" },
  BOB: { name: "Bolivian Boliviano", nameCn: "玻利维亚诺" },
  BRL: { name: "Brazilian Real", nameCn: "巴西雷亚尔" },
  BSD: { name: "Bahamian Dollar", nameCn: "巴哈马元" },
  BTN: { name: "Bhutanese Ngultrum", nameCn: "不丹努尔特鲁姆" },
  BWP: { name: "Botswana Pula", nameCn: "博茨瓦纳普拉" },
  BYN: { name: "Belarusian Ruble", nameCn: "白俄罗斯卢布" },
  BZD: { name: "Belize Dollar", nameCn: "伯利兹元" },
  CAD: { name: "Canadian Dollar", nameCn: "加元" },
  CDF: { name: "Congolese Franc", nameCn: "刚果法郎" },
  CHF: { name: "Swiss Franc", nameCn: "瑞士法郎" },
  CLP: { name: "Chilean Peso", nameCn: "智利比索" },
  CNY: { name: "Chinese Yuan", nameCn: "人民币" },
  CNH: { name: "Chinese Yuan (Offshore)", nameCn: "离岸人民币" },
  COP: { name: "Colombian Peso", nameCn: "哥伦比亚比索" },
  CRC: { name: "Costa Rican Colon", nameCn: "哥斯达黎加科朗" },
  CUP: { name: "Cuban Peso", nameCn: "古巴比索" },
  CVE: { name: "Cape Verdean Escudo", nameCn: "佛得角埃斯库多" },
  CZK: { name: "Czech Koruna", nameCn: "捷克克朗" },
  DJF: { name: "Djiboutian Franc", nameCn: "吉布提法郎" },
  DKK: { name: "Danish Krone", nameCn: "丹麦克朗" },
  DOP: { name: "Dominican Peso", nameCn: "多米尼加比索" },
  DZD: { name: "Algerian Dinar", nameCn: "阿尔及利亚第纳尔" },
  EGP: { name: "Egyptian Pound", nameCn: "埃及镑" },
  ERN: { name: "Eritrean Nakfa", nameCn: "厄立特里亚纳克法" },
  ETB: { name: "Ethiopian Birr", nameCn: "埃塞俄比亚比尔" },
  EUR: { name: "Euro", nameCn: "欧元" },
  FJD: { name: "Fijian Dollar", nameCn: "斐济元" },
  FKP: { name: "Falkland Islands Pound", nameCn: "福克兰群岛镑" },
  GBP: { name: "British Pound", nameCn: "英镑" },
  GEL: { name: "Georgian Lari", nameCn: "格鲁吉亚拉里" },
  GHS: { name: "Ghanaian Cedi", nameCn: "加纳塞地" },
  GIP: { name: "Gibraltar Pound", nameCn: "直布罗陀镑" },
  GMD: { name: "Gambian Dalasi", nameCn: "冈比亚达拉西" },
  GNF: { name: "Guinean Franc", nameCn: "几内亚法郎" },
  GTQ: { name: "Guatemalan Quetzal", nameCn: "危地马拉格查尔" },
  GYD: { name: "Guyanese Dollar", nameCn: "圭亚那元" },
  HKD: { name: "Hong Kong Dollar", nameCn: "港币" },
  HNL: { name: "Honduran Lempira", nameCn: "洪都拉斯伦皮拉" },
  HRK: { name: "Croatian Kuna", nameCn: "克罗地亚库纳" },
  HTG: { name: "Haitian Gourde", nameCn: "海地古德" },
  HUF: { name: "Hungarian Forint", nameCn: "匈牙利福林" },
  IDR: { name: "Indonesian Rupiah", nameCn: "印尼盾" },
  ILS: { name: "Israeli New Shekel", nameCn: "以色列谢克尔" },
  INR: { name: "Indian Rupee", nameCn: "印度卢比" },
  IQD: { name: "Iraqi Dinar", nameCn: "伊拉克第纳尔" },
  IRR: { name: "Iranian Rial", nameCn: "伊朗里亚尔" },
  ISK: { name: "Icelandic Krona", nameCn: "冰岛克朗" },
  JMD: { name: "Jamaican Dollar", nameCn: "牙买加元" },
  JOD: { name: "Jordanian Dinar", nameCn: "约旦第纳尔" },
  JPY: { name: "Japanese Yen", nameCn: "日元" },
  KES: { name: "Kenyan Shilling", nameCn: "肯尼亚先令" },
  KGS: { name: "Kyrgyzstani Som", nameCn: "吉尔吉斯索姆" },
  KHR: { name: "Cambodian Riel", nameCn: "柬埔寨瑞尔" },
  KMF: { name: "Comorian Franc", nameCn: "科摩罗法郎" },
  KRW: { name: "Korean Won", nameCn: "韩元" },
  KWD: { name: "Kuwaiti Dinar", nameCn: "科威特第纳尔" },
  KYD: { name: "Cayman Islands Dollar", nameCn: "开曼群岛元" },
  KZT: { name: "Kazakhstani Tenge", nameCn: "哈萨克斯坦腾格" },
  LAK: { name: "Lao Kip", nameCn: "老挝基普" },
  LBP: { name: "Lebanese Pound", nameCn: "黎巴嫩镑" },
  LKR: { name: "Sri Lankan Rupee", nameCn: "斯里兰卡卢比" },
  LRD: { name: "Liberian Dollar", nameCn: "利比里亚元" },
  LSL: { name: "Lesotho Loti", nameCn: "莱索托洛蒂" },
  LYD: { name: "Libyan Dinar", nameCn: "利比亚第纳尔" },
  MAD: { name: "Moroccan Dirham", nameCn: "摩洛哥迪拉姆" },
  MDL: { name: "Moldovan Leu", nameCn: "摩尔多瓦列伊" },
  MGA: { name: "Malagasy Ariary", nameCn: "马达加斯加阿里亚里" },
  MKD: { name: "Macedonian Denar", nameCn: "北马其顿第纳尔" },
  MMK: { name: "Myanmar Kyat", nameCn: "缅甸缅元" },
  MNT: { name: "Mongolian Tugrik", nameCn: "蒙古图格里克" },
  MOP: { name: "Macanese Pataca", nameCn: "澳门元" },
  MRU: { name: "Mauritanian Ouguiya", nameCn: "毛里塔尼亚乌吉亚" },
  MUR: { name: "Mauritian Rupee", nameCn: "毛里求斯卢比" },
  MVR: { name: "Maldivian Rufiyaa", nameCn: "马尔代夫拉菲亚" },
  MWK: { name: "Malawian Kwacha", nameCn: "马拉维克瓦查" },
  MXN: { name: "Mexican Peso", nameCn: "墨西哥比索" },
  MYR: { name: "Malaysian Ringgit", nameCn: "马来西亚林吉特" },
  MZN: { name: "Mozambican Metical", nameCn: "莫桑比克梅蒂卡尔" },
  NAD: { name: "Namibian Dollar", nameCn: "纳米比亚元" },
  NGN: { name: "Nigerian Naira", nameCn: "尼日利亚奈拉" },
  NIO: { name: "Nicaraguan Cordoba", nameCn: "尼加拉瓜科多巴" },
  NOK: { name: "Norwegian Krone", nameCn: "挪威克朗" },
  NPR: { name: "Nepalese Rupee", nameCn: "尼泊尔卢比" },
  NZD: { name: "New Zealand Dollar", nameCn: "新西兰元" },
  OMR: { name: "Omani Rial", nameCn: "阿曼里亚尔" },
  PAB: { name: "Panamanian Balboa", nameCn: "巴拿马巴波亚" },
  PEN: { name: "Peruvian Sol", nameCn: "秘鲁索尔" },
  PGK: { name: "Papua New Guinean Kina", nameCn: "巴布亚新几内亚基那" },
  PHP: { name: "Philippine Peso", nameCn: "菲律宾比索" },
  PKR: { name: "Pakistani Rupee", nameCn: "巴基斯坦卢比" },
  PLN: { name: "Polish Zloty", nameCn: "波兰兹罗提" },
  PYG: { name: "Paraguayan Guarani", nameCn: "巴拉圭瓜拉尼" },
  QAR: { name: "Qatari Rial", nameCn: "卡塔尔里亚尔" },
  RON: { name: "Romanian Leu", nameCn: "罗马尼亚列伊" },
  RSD: { name: "Serbian Dinar", nameCn: "塞尔维亚第纳尔" },
  RUB: { name: "Russian Ruble", nameCn: "卢布" },
  RWF: { name: "Rwandan Franc", nameCn: "卢旺达法郎" },
  SAR: { name: "Saudi Riyal", nameCn: "沙特里亚尔" },
  SBD: { name: "Solomon Islands Dollar", nameCn: "所罗门群岛元" },
  SCR: { name: "Seychellois Rupee", nameCn: "塞舌尔卢比" },
  SDG: { name: "Sudanese Pound", nameCn: "苏丹镑" },
  SEK: { name: "Swedish Krona", nameCn: "瑞典克朗" },
  SGD: { name: "Singapore Dollar", nameCn: "新加坡元" },
  SHP: { name: "Saint Helena Pound", nameCn: "圣赫勒拿镑" },
  SLE: { name: "Sierra Leonean Leone", nameCn: "塞拉利昂利昂" },
  SLL: { name: "Sierra Leonean Leone (old)", nameCn: "塞拉利昂利昂" },
  SOS: { name: "Somali Shilling", nameCn: "索马里先令" },
  SRD: { name: "Surinamese Dollar", nameCn: "苏里南元" },
  SSP: { name: "South Sudanese Pound", nameCn: "南苏丹镑" },
  STN: { name: "Sao Tomean Dobra", nameCn: "圣多美多布拉" },
  SYP: { name: "Syrian Pound", nameCn: "叙利亚镑" },
  SZL: { name: "Eswatini Lilangeni", nameCn: "斯威士兰里兰吉尼" },
  THB: { name: "Thai Baht", nameCn: "泰铢" },
  TJS: { name: "Tajikistani Somoni", nameCn: "塔吉克斯坦索莫尼" },
  TMT: { name: "Turkmenistani Manat", nameCn: "土库曼斯坦马纳特" },
  TND: { name: "Tunisian Dinar", nameCn: "突尼斯第纳尔" },
  TOP: { name: "Tongan Paanga", nameCn: "汤加潘加" },
  TRY: { name: "Turkish Lira", nameCn: "土耳其里拉" },
  TTD: { name: "Trinidadian Dollar", nameCn: "特立尼达和多巴哥元" },
  TWD: { name: "New Taiwan Dollar", nameCn: "新台币" },
  TZS: { name: "Tanzanian Shilling", nameCn: "坦桑尼亚先令" },
  UAH: { name: "Ukrainian Hryvnia", nameCn: "乌克兰格里夫纳" },
  UGX: { name: "Ugandan Shilling", nameCn: "乌干达先令" },
  USD: { name: "US Dollar", nameCn: "美元" },
  UYU: { name: "Uruguayan Peso", nameCn: "乌拉圭比索" },
  UZS: { name: "Uzbekistani Som", nameCn: "乌兹别克斯坦苏姆" },
  VES: { name: "Venezuelan Bolivar", nameCn: "委内瑞拉玻利瓦尔" },
  VND: { name: "Vietnamese Dong", nameCn: "越南盾" },
  VUV: { name: "Vanuatu Vatu", nameCn: "瓦努阿图瓦图" },
  WST: { name: "Samoan Tala", nameCn: "萨摩亚塔拉" },
  XAF: { name: "Central African CFA Franc", nameCn: "中非法郎" },
  XCD: { name: "East Caribbean Dollar", nameCn: "东加勒比元" },
  XDR: { name: "Special Drawing Rights", nameCn: "特别提款权" },
  XOF: { name: "West African CFA Franc", nameCn: "西非法郎" },
  XPF: { name: "CFP Franc", nameCn: "太平洋法郎" },
  YER: { name: "Yemeni Rial", nameCn: "也门里亚尔" },
  ZAR: { name: "South African Rand", nameCn: "南非兰特" },
  ZMW: { name: "Zambian Kwacha", nameCn: "赞比亚克瓦查" },
};
